version: '3.8'

services:
   web:
      build: 
        context: ./app
        dockerfile: Dockerfile.prod
      command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
      volumes:
         - static_volume:/home/app/web/staticfiles
         - media_volume:/home/app/web/mediafiles
      expose:
         - 8000
      env_file:
         - ./.env.prod
      depends_on:
         - db
   db:
      image: postgres:13.0-alpine
      volumes:
         - postgres_data:/var/lib/postgresql/data/
      env_file:
         - ./.env.prod.db
   nginx:
      build: ./nginx
      volumes:
         - static_volume:/home/app/web/staticfiles
         - media_volume:/home/app/web/mediafiles
         #- ./certbot/conf:/etc/letsencrypt
         #- ./certbot/www:/var/www/certbot
      ports:
        - 80:80
      depends_on:
        - web
   certbot:
      image: certbot/certbot
      volumes:
         - ./certbot/conf:/etc/letsencrypt
         - ./certbot/www:/var/www/certbot
volumes:
   postgres_data:
   static_volume:
   media_volume:
